language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- pypy

matrix:
  include:
  - python: '2.7'
    # using a different option due to pytest-addopts pytester issues
    env: PYTEST_XADDOPTS="-n 3 --runslowtests"
  allow_failures:
  - python: pypy
install:
- pip install -U setuptools setuptools_scm
- pip install pytest~=2.9.0 pytest-xdist~=1.17.0
- pip install -U . --force-reinstall
script:
- py.test --lsof $PYTEST_XADDOPTS
